### ISSUE TITLE
Feat: Ignore words in code references

### ISSUE THREAD

**Issue by GuySartorelli** [greyscaled/markdownlint-rule-title-case-style#79]
## Description

In our documentation, we sometimes have code references inside headers, e.g. ``## My `ModelAdmin` heading``

At the moment we can't use this rule to lint the heading style (we use sentence style) without adding a whooole load of exceptions in the ignore list. If we could just say `include_code: false` that would be incredibly useful for this use case.

**Comment by greyscaled** [comment]
Hey @GuySartorelli , thanks for checking out this little project and letting me know about the use case.

That's definitely a common scenario and I think a higher level configuration is appropriate as you've mentioned.

If you run into any other problems or suggestions they're welcome of course.

I'll ping back once there's a commit in place, and once again thanks!

**Comment by greyscaled** [comment]
@GuySartorelli I released a `0.4.2`! Let me know if something else comes up.

A heads up that the package was rewritten to ESM, and seems to work best with `.markdownlint-cli2.mjs` config files: https://www.npmjs.com/package/markdownlint-rule-title-case-style#markdownlint-cli2

Cheers

**Comment by GuySartorelli** [comment]
That's fantastic, thank you!

> A heads up that the package was rewritten to ESM, and seems to work best with `.markdownlint-cli2.mjs` config files

I did see that in the readme, but I'm struggling to understand why that is. Are there some known issues with the [markdown-cli](https://www.npmjs.com/package/markdownlint-cli) package?

**Comment by greyscaled** [comment]
> I'm struggling to understand why that is

I'm in a similar boat and happy to hear ideas or opinions. I was originally confused by the two CLI packages when putting this rule together a few months back.

What I do know, is that [the author](https://github.com/DavidAnson) of [`markdownlint`](https://github.com/DavidAnson/markdownlint) created [`markdownlint-cli2`](https://github.com/DavidAnson/markdownlint-cli2) and it seems decently maintained. He wrote an article on the motivation for `cli-2` here: https://dlaa.me/blog/post/markdownlintcli2

and if you check out the contributors, you can see that he's the primary maintainer of the original CLI: https://github.com/igorshubovych/markdownlint-cli/graphs/contributors

> Are there some known issues...

I haven't spent enough time looking into it yet, since I was already using `markdownlint-cli2`. I _vaguely_ recall that I wasn't initially sure how to pass custom rule config through `markdownlint-cli`. I opened: https://github.com/greyscaled/markdownlint-rule-title-case-style/issues/93 to investigate it. Hopefully I can figure out how to support both, without having to go back to CJS. If it does require going back to CJS, I suppose I can just bite that bullet 😆.

**Comment by GuySartorelli** [comment]
Awesome, thanks for that context 💙
